### ISSUE TITLE
Do not autoplay the next recording if the current one is deleted

### ISSUE THREAD

**Issue by tibbi** [SimpleMobileTools/Simple-Voice-Recorder#37]

**Comment by mare5x** [comment]
@tibbi This is still an issue. If you delete a recording while it is being played, the next recording will start playing. I think this should be fixed because it is counter-intuitive (to me, at least).

Changing the following line:
https://github.com/SimpleMobileTools/Simple-Voice-Recorder/blob/aead0af63e060e86ec6a63efea7bf5d8aba786da/app/src/main/kotlin/com/simplemobiletools/voicerecorder/fragments/PlayerFragment.kt#L277 to `playOnPreparation = playOnPrepared` should fix the issue.
